name: dropdown_banner
description: Manages the creation and animation of banner ui elements that are useful for displaying warnings and updates to users.
version: 1.4.0
homepage: https://github.com/flyrboy96/flutter_dropdown_banner
author: Bruce Brookshire <bruce.t.brookshire@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_notification_center:
    git:
      url: https://github.com/brackendev/dart_notification_center.git
      ref: 8233ef080741739cdadf5dd6653f7ee8ad1fddf4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
